const platform=document.getElementById('platform'),controls=document.getElementById('host-controls');
const KEY='yuanlei-u4-host-demo-v1';let prefs={pinned:false,projectFolded:false,width:204};try{Object.assign(prefs,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{}
let overlayWidth=matchMedia('(max-width:1100px)').matches;let open=false,dismissed=false,compare='explicit',mobileOpen=false,lastTrigger=null;const narrow=()=>matchMedia('(max-width:700px)').matches;
function persist(){localStorage.setItem(KEY,JSON.stringify(prefs))}
function apply(){document.body.classList.toggle('platform-pinned',prefs.pinned);document.body.classList.toggle('project-folded',prefs.projectFolded);document.body.classList.toggle('project-mobile-open',mobileOpen);document.body.style.setProperty('--project-width',prefs.width+'px');const expanded=!dismissed&&(open||(!overlayWidth&&prefs.pinned));platform.classList.toggle('expanded',expanded);platform.inert=narrow()&&!expanded;document.getElementById('expand-platform')?.setAttribute('aria-expanded',String(expanded));document.getElementById('toggle-project')?.setAttribute('aria-expanded',String(narrow()?mobileOpen:!prefs.projectFolded));document.getElementById('pin-platform').innerHTML='<span class="platform-icon">⌖</span><span class="platform-label">'+(prefs.pinned?'取消固定':'固定平台展开')+'</span>';document.getElementById('pin-platform').setAttribute('aria-label',prefs.pinned?'取消固定':'固定平台展开');const global=location.hash.startsWith('#b/');document.body.classList.toggle('global-route',global);document.getElementById('toggle-project').disabled=global;document.getElementById('host-context').textContent=global?'平台跨项目收件箱 · 全部合成':(location.hash.includes('/beta/')?'展陈筹备 · B':'采购协同 · A')+' / 项目工作空间 · 全部合成';}
platform.innerHTML=`<strong class="platform-item"><span class="platform-icon">元</span><span class="platform-label">元垒平台</span></strong><button class="platform-item" id="close-platform" aria-label="收起平台导航"><span class="platform-icon">‹</span><span class="platform-label">收起平台导航</span></button><button class="platform-item" id="pin-platform">固定平台展开</button><hr><button class="platform-item" disabled title="未实现"><span class="platform-icon">＋</span><span class="platform-label">新聊天（未实现）</span></button><button class="platform-item" disabled title="未实现"><span class="platform-icon">◇</span><span class="platform-label">智能体管理（未实现）</span></button><button class="platform-item" id="host-inbox" aria-label="平台跨项目收件箱"><span class="platform-icon">◌</span><span class="platform-label">跨项目收件箱</span></button><button class="platform-item" id="host-project" aria-label="回到当前项目管理概览"><span class="platform-icon">▦</span><span class="platform-label">当前项目</span></button><hr><p class="host-note">宿主示意<br>未接真实平台</p>`;
controls.innerHTML=`<button class="btn small" id="expand-platform" aria-controls="platform" aria-expanded="false">平台导航</button><button class="btn small" id="toggle-project" aria-expanded="true">项目导航</button><label class="context">同空间比较 <select id="host-compare" class="btn small" aria-label="平台展开对照"><option value="explicit">显式展开 / 固定</option><option value="hover">悬浮 / 焦点展开实验</option></select></label><label class="context">项目宽度 <select id="project-width" class="btn small" aria-label="项目导航宽度"><option value="180">紧凑 180</option><option value="204">默认 204</option><option value="260">宽 260</option></select></label><span class="context" id="host-context"></span>`;
document.getElementById('project-width').value=String(prefs.width);
controls.addEventListener('click',ev=>{if(ev.target.id==='expand-platform'){lastTrigger=ev.target;dismissed=false;open=!open;apply();if(open)document.getElementById('close-platform').focus()}if(ev.target.id==='toggle-project'){if(narrow())mobileOpen=!mobileOpen;else{prefs.projectFolded=!prefs.projectFolded;persist()}apply()}});
controls.addEventListener('change',ev=>{if(ev.target.id==='host-compare'){compare=ev.target.value;open=false;dismissed=false;apply()}if(ev.target.id==='project-width'){prefs.width=Number(ev.target.value);persist();apply()}});
platform.addEventListener('click',ev=>{if(ev.target.closest('#close-platform')){prefs.pinned=false;open=false;persist();apply();(lastTrigger||document.getElementById('expand-platform')).focus()}if(ev.target.closest('#pin-platform')){prefs.pinned=!prefs.pinned;dismissed=false;open=prefs.pinned;persist();apply()}if(ev.target.closest('#host-inbox')){location.hash='#b/'+(location.hash.includes('/beta/')?'beta':'alpha')+'/queue'}if(ev.target.closest('#host-project')){const project=location.hash.includes('/beta/')?'beta':'alpha';location.hash='#a/'+project+'/overview'}});
const hoverAllowed=()=>compare==='hover'&&matchMedia('(hover:hover) and (pointer:fine)').matches;
platform.addEventListener('pointerenter',()=>{if(hoverAllowed()){open=true;dismissed=false;apply()}});platform.addEventListener('pointerleave',()=>{if(hoverAllowed()&&!platform.contains(document.activeElement)&&!prefs.pinned){open=false;apply()}});
platform.addEventListener('focusin',()=>{if(compare==='hover'){open=true;dismissed=false;apply()}});platform.addEventListener('focusout',()=>{setTimeout(()=>{if(compare==='hover'&&!platform.contains(document.activeElement)&&!platform.matches(':hover')&&!prefs.pinned){open=false;apply()}},0)});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&platform.classList.contains('expanded')&&!document.body.classList.contains('full-screen')&&!document.querySelector('.overlay')&&(!prefs.pinned||matchMedia('(max-width:1100px)').matches)){open=false;dismissed=true;apply();document.getElementById('expand-platform').focus()}});
window.addEventListener('hashchange',()=>{if(narrow())mobileOpen=false;apply()});window.addEventListener('resize',()=>{const next=matchMedia('(max-width:1100px)').matches;if(next!==overlayWidth){open=false;dismissed=false;overlayWidth=next}apply()});apply();
