import{createApp,h,ref,onMounted,nextTick}from'/runtime/vue.js';
import{drawR1,validateScene,validateDefinition,definition}from'./r1.js';
const B=(name,click,cls='')=>h('button',{class:'btn '+cls,onClick:click},name);
createApp({setup(){
 const scene=ref(null),theme=ref(new URLSearchParams(location.search).get('theme')==='dark'?'dark':'light'),showRoute=ref(new URLSearchParams(location.search).get('path')!=='0'),r1Selected=ref(null),r2Selected=ref(null),frame=ref(null),srcdoc=ref(''),failure=ref(''),sourceError=ref(''),ready=ref(false),log=ref([]),variant=ref('normal');let channel='',timeout,revision=0;
 const record=s=>{log.value.unshift(s);log.value=log.value.slice(0,10)};
 const snapshot=()=>{if(ready.value&&scene.value)frame.value?.contentWindow.postMessage({channel,type:'snapshot',scene:JSON.parse(JSON.stringify(scene.value)),theme:theme.value,showRoute:showRoute.value,selectedId:r2Selected.value?.id||null},'*')};
 const fetchScene=async(state='normal')=>{try{const r=await fetch('/spatial-scene?project=alpha&state='+state,{credentials:'omit'}),s=await r.json();if(!r.ok)throw Error(r.status+' '+s.error);validateScene(s);scene.value=s;r1Selected.value=null;r2Selected.value=null;sourceError.value='';snapshot();record('同源快照：'+s.source+' · '+s.as_of)}catch(e){sourceError.value=e.message;record('源/数据拒绝：'+e.message)}};
 const boot=async v=>{const rev=++revision;variant.value=v;ready.value=false;failure.value='';r2Selected.value=null;srcdoc.value='';clearTimeout(timeout);channel=crypto.randomUUID();try{const r=await fetch('/r2-bundle?variant='+v,{credentials:'omit'}),d=await r.json();if(!r.ok)throw Error(r.status+' '+d.error);const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(d.bundle)))].map(b=>b.toString(16).padStart(2,'0')).join('');if(digest!==d.sha256)throw Error('bundle_digest_mismatch');if(rev!==revision)return;
 const bootstrap=`window.__CHANNEL__=${JSON.stringify(channel)};window.__HOST_ORIGIN__=${JSON.stringify(location.origin)};window.addEventListener('error',e=>parent.postMessage({channel:window.__CHANNEL__,type:'failure',error:e.message},window.__HOST_ORIGIN__));\n`;
 const js=(bootstrap+d.bundle).replace(/<\/script/gi,'<\\/script');const bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(js)));const hash=btoa(String.fromCharCode(...bytes));if(rev!==revision)return;
 srcdoc.value=`<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'sha256-${hash}'; style-src 'unsafe-inline'; connect-src 'none'; img-src 'none'; frame-src 'none'; form-action 'none'; base-uri 'none'"><style>body{margin:0;font:14px -apple-system,sans-serif}main{color:#182d3d;background:#fff}main[data-theme=dark]{color:#e2ecf2;background:#172733}svg{display:block;width:100%;max-height:400px}p{padding:8px 12px;margin:0;line-height:1.7}button{margin-left:8px;padding:7px}g{cursor:pointer}g:focus{outline:2px solid #116d69}</style></head><body><div id="scene"></div><script>${js}</script></body></html>`;
 await nextTick();timeout=setTimeout(()=>{if(rev===revision&&!ready.value&&!failure.value){failure.value='startup_timeout';record('R2 启动超时；保留 R1')}} ,2000);
 }catch(e){if(rev===revision){failure.value=e.message;record('R2 加载失败：'+e.message)}}};
 const navigate=async object=>{if(!object||!['kind','id','work'].every(k=>object[k]===undefined||typeof object[k]==='string')||Object.keys(object).some(k=>!['kind','id','work'].includes(k))){record('导航拒绝：对象描述输入不合格');return}const r=await fetch('/resolve-navigation?'+new URLSearchParams({project:'alpha',...object}),{credentials:'omit'}),d=await r.json();record('导航回读：'+r.status+' '+(d.error||d.id));if(r.ok){const saved=JSON.parse(sessionStorage.getItem('yuanlei-u3-demo-v1')||'{}');saved.returns??={};saved.returns['alpha/'+(d.work||d.id)]={page:'space',theme:theme.value,showRoute:showRoute.value};sessionStorage.setItem('yuanlei-u3-demo-v1',JSON.stringify(saved));location.href=d.target}else sourceError.value=d.error};
 window.addEventListener('message',e=>{const d=e.data;if(e.source!==frame.value?.contentWindow){if(d?.type==='navigate')record('消息拒绝：source');return}if(e.origin!=='null'){record('消息拒绝：origin');return}if(d?.channel!==channel){record('消息拒绝：channel');return}if(d.type==='ready'){ready.value=true;snapshot();record('R2 ready · opaque origin · snapshot bridge');return}if(d.type==='failure'){failure.value=d.error;ready.value=false;clearTimeout(timeout);record('R2 运行失败：'+d.error);return}if(d.type==='probe'){record('隔离探针：'+JSON.stringify(d.probe));return}if(d.type==='selected'){const z=scene.value?.zones.find(z=>z.id===d.id);if(z)r2Selected.value=z;else record('选择拒绝：不属于当前场景');return}if(d.type==='navigate'){const expected=r2Selected.value?.object;if(Object.keys(d).some(k=>!['channel','type','object'].includes(k))||!expected||JSON.stringify(d.object)!==JSON.stringify(expected)){record('导航拒绝：非当前选择/任意URL/额外输入');return}navigate(d.object)}});
 onMounted(()=>{fetchScene();boot('normal')});
 const panel=(name,body)=>h('section',{class:'panel panel-pad'},[h('h2',name),body]);
 return()=>h('main',{'data-theme':theme.value},[
 h('div',{class:'prototypebar'},[h('span',{class:'mark'},'U3 第二轮 · 合成空间 · R1 / R2 隔离对照'),h('a',{href:'index.html#a/alpha/overview',class:'btn'},'← 回连续任务'),B(theme.value==='light'?'☾ 深色':'☀ 浅色',()=>{theme.value=theme.value==='light'?'dark':'light';snapshot()}),B(showRoute.value?'隐藏通行路径':'显示通行路径',()=>{showRoute.value=!showRoute.value;snapshot()})]),
 h('div',{class:'lab-header'},[h('h1','同一个小空间，两种表达路径'),h('p',{class:'subtext'},'任务：辨认 C 区阻挡，沿绕行线从 A 到 D；选 B 区进入准确结果 R4。坐标单位为合成示意米，非测绘或真实通行建议。')]),
 h('div',{class:'lab-body'},[
 h('div',{class:'notice'},'两侧消费同一宿主校验快照，场景只属于示例 A。R1 新增一个有限坐标素材；R2 为手写 SFC 编译样例，未调用 Agent 生成。'),
 scene.value&&scene.value.zones.length===0?h('div',{class:'notice'},'空场景：暂无区域和路径，不等于源读取失败。'):null,
 sourceError.value?h('div',{class:'notice error',role:'alert'},'读取/验证失败：'+sourceError.value+'；上次有效场景和时间保留。'):null,
 h('div',{class:'actions',style:'margin-bottom:18px'},[B('刷新同源数据',()=>fetchScene()),B('空场景',()=>fetchScene('empty')),B('源读取失败',()=>fetchScene('error')),B('越界坐标',()=>fetchScene('malformed')),B('R1 定义脚本拒绝',()=>{try{validateDefinition({...definition,code:'alert(1)'})}catch(e){record(e.message)}})]),
 h('div',{class:'compare-line'},[
 panel('R1 · 有限坐标素材',scene.value?h('div',[drawR1(scene.value,z=>r1Selected.value=z,showRoute.value),r1Selected.value?h('p',{class:'subtext'},[r1Selected.value.label+' · '+r1Selected.value.status+' ',B('查看准确对象',()=>navigate(r1Selected.value.object),'small')]):h('p',{class:'subtext'},'选择区域，核对其对象再进入办理。'),h('p',{class:'small-note'},'区域、状态、路径和对象引用；曲线、分层、热区及自动寻路未实现。')]):h('p','等待场景')),
 panel('R2 · 编译 Vue / opaque iframe',h('div',[failure.value?h('div',{class:'notice error',role:'alert'},'R2 失败：'+failure.value+'。本页 R1 仍可用，未把回退称为 R2 成功。'):null,srcdoc.value&&!failure.value?h('iframe',{key:channel,ref:frame,srcdoc:srcdoc.value,sandbox:'allow-scripts',title:'R2 隔离 Vue 小空间',class:'space-frame',referrerpolicy:'no-referrer'}):null,h('p',{class:'small-note'},'仅脚本权限；没有 same-origin、顶层导航、表单或弹窗许可。浏览器内动态编译未启用。')]))]),
 h('div',{class:'actions',style:'margin:18px 0'},[B('重载正常 R2',()=>boot('normal')),B('R2 运行失败',()=>boot('crash')),B('R2 隔离探针',()=>boot('probe')),B('R2 构建包缺失',()=>boot('missing')),B('R2 摘要错配',()=>boot('bad-digest')),B('拒绝跨项目对象',()=>navigate({kind:'result',id:'b-r1',work:'b1'}))]),
 panel('来源、能力边界与记录',h('div',[h('p',{class:'subtext'},scene.value?`${scene.value.source} · 截至 ${scene.value.as_of} · 取得 ${scene.value.fetched_at}`:'无成功快照'),h('p',{class:'subtext'},'同源与几何效果不等于正式数据权限或创作平台通过。路径由源给定；没有自动避障算法。R2 不提供代码编辑器/任意依赖，编译固定源码使用当前仓库依赖。'),...log.value.map(s=>h('p',{class:'small-note'},s))]))
 ])]);
}}).mount('#spatial');
